---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# munifacil

<!-- badges: start -->
<!-- badges: end -->

O pacote munifacil serve para juntar municipios facilmente!

```{r, eval = FALSE}

#remotes::install_github("curso-r/munifacil")

library(munifacil)

arquivo <- system.file("extdata/exemplo.xlsx", package = "munifacil")

sua_base <- readxl::read_excel(arquivo) %>% 
  janitor::clean_names() %>% 
  dplyr::select(
    municipio = 1, 
    uf = 3,
    ibge = 2
  ) %>% 
  dplyr::distinct(municipio, .keep_all = TRUE)

resultado <- sua_base %>% 
  limpar_colunas(municipio, uf) %>% 
  # cria uma coluna "uf_join"
  incluir_codigo_ibge()

resultado %>% 
  dplyr::filter(is.na(id_municipio))

# deu certo?
resultado %>% 
  dplyr::count(ibge == id_municipio)

# deu!
```


## Tarefas

- [ ] Escrever uma solução para fazer correções manuais
- [ ] Facilitar o trabalho de adicionar opções na base `depara_muni_codigo`
- [ ] Implementar uma opção de fuzzy join
